force-app/main/default/objects/ForeignExchangeTrade__c/ForeignExchangeTrade__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store trade records</description>
    <label>Foreign Exchange Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Foreign Exchange Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ForeignExchangeTrade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ForeignExchangeTrade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTC</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <description>Global picklist to store currency codes</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestFactory.cls
/************************************************************************************************
 * Test Factory Class to generate data for test classes
 * Created:
 * Modified:
 ************************************************************************************************/
public class TestFactory {
    
    /********************************************************************************************
     * Method to create and return instance of ForeignExchangeTrade__c object
     * 
     ********************************************************************************************/
    public static ForeignExchangeTrade__c createForeignExchangeTrade() {
        ForeignExchangeTrade__c inst = new ForeignExchangeTrade__c();
        inst.SellAmount__c = 100;
        inst.SellCurrency__c = 'EUR';
        inst.BuyAmount__c = 8500;
        inst.BuyCurrency__c = 'INR';
        inst.Rate__c = 85;
        return inst;
    }
}