force-app/main/default/objects/ForeignExchangeTrade__c/ForeignExchangeTrade__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store trade records</description>
    <label>Foreign Exchange Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Foreign Exchange Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ForeignExchangeTrade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ForeignExchangeTrade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ForeignExchangeTrade__c/fields/DateBooked__c.field-meta.xml
<CustomField>
    <fullName>DateBooked__c</fullName>
    <defaultValue>DATETIMEVALUE(&quot;YEAR(date)-MONTH(date)-DAY(date) HOUR(expression):MINUTE(expression):SECOND(expression)&quot;)</defaultValue>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTC</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <description>Global picklist to store currency codes</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ForeignExchangeRateTradeController.cls
/************************************************************************************************
 * Class to handle actions on Foreign Exchange Trade Object
 * Created:
 * Modified:
 ************************************************************************************************/
public with sharing class ForeignExchangeRateTradeController {
   
    /********************************************************************************************
     * Method to get foreign exchange records based sorted by descending order
     * Created:
     * Modified:
     ********************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<ForeignExchangeTrade__c> getTradeRecords(){
        return [SELECT Id, Name, SellCurrency__c, SellAmount__c, BuyCurrency__c, BuyAmount__c, Rate__c, DateBooked__c FROM ForeignExchangeTrade__c ORDER BY DateBooked__c DESC];
    }

    /********************************************************************************************
     * Method to return exchange rate between 2 currencies
     * Created:
     * Modified:
     ********************************************************************************************/
    @AuraEnabled
    public static Decimal getExchangeRate(String sellCurrencyCode, String buyCurrencyCode){
        /*HttpResponse hRes = new HttpResponse();
        HttpCalloutHandler.HttpRequestWrapper requestWrapperIntst = new HttpCalloutHandler.HttpRequestWrapper();

        Map<String, String> paramMap = new Map<String, String>();
        paramMap.put('access_key', '8932fca849fb1029c055bc6635746db7');
        paramMap.put('format', '1');

        requestWrapperIntst.method = 'GET';
        requestWrapperIntst.endPoint = 'http://data.fixer.io/api/latest';//save in Label
        requestWrapperIntst.urlParamMap = paramMap;

        hRes = HttpCalloutHandler.makeCallout(requestWrapperIntst);
        Decimal exchangeRate = getExchangeRate(hRes, sellCurrencyCode, buyCurrencyCode);

        return exchangeRate;*/
        return 2;
    }

    /********************************************************************************************
     * Method to read Http reponse and get actual conversion rate
     * Created:
     * Modified:
     ********************************************************************************************/
    private static Decimal getExchangeRate(HttpResponse response, String sellCurrencyCode, String buyCurrencyCode){
        Decimal exchangeRate;
        Map<String, Object> jsonReponseObject = (Map<String, Object>)Json.deserializeUntyped(response.getBody());
        Map<String, Object> rates = (Map<String, Object>)jsonReponseObject.get('rates');
        
        exchangeRate = (Decimal)rates.get(buyCurrencyCode)/(Decimal)rates.get(sellCurrencyCode);
        //                              84.42/1.13 = 74.42 (USD to INR sell-buy)
        //                              1.13/1     = 1.13  (EUR to USD sell-buy)

        return exchangeRate;
    }
}